main: main.o
	gcc main.c -o main
	ob=$(wordlist  2,8,I like Linux C programs)
	echo $(ob)
	ob=$(notdir /root/install.log /home/dingguiqiang/Destop/C/main.c Makefile)
	echo $(ob)
.PHONY:clean
clean:
	rm *.o main 
